version: '3'
services:

  kibana:
    image: kibana:${KIBANA_VERSION}
    container_name: kibana
    hostname: kibana
    restart: always
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /data/elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml

  logstash:
    image: logstash:${LOGSTASH_VERSION}
    container_name: logstash
    hostname: logstash
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
    links:
      - elasticsearch
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /data/elk/logstash/pipeline:/usr/share/logstash/pipeline
      - /data/elk/logstash/patterns:/usr/share/logstash/patterns
      - /data/elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml

  elasticsearch:
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    container_name: elasticsearch
    hostname: elasticsearch
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - "9200:9200"
    volumes:
      - /data/elk/elasticsearch/data:/usr/share/elasticsearch/data
      - /data/elk/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - /data/elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/elasticsearch.yml

  filebeat:
    image: elastic/filebeat:${FILEBEAT_VERSION}
    container_name: filebeat
    restart: always
    volumes:
      - /data/elk/filebeat/modules.d:/usr/share/filebeat/modules.d
      - /data/elk/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml

networks:
  default:
    driver: bridge
